# Summary of bootstrap fit the logistic model to the simulated data

library(tidyverse)
library(here)

# Directories used
fit_dir <- here("model-fit")

# Functions ===================================================================

#' Converts the bootstrap results from long to wide
bootfit_widen <- function(bootfit) {
  bootfit %>%
    select(term, estimate, ind) %>%
    pivot_wider(names_from = term, values_from = estimate)
}

#' Calculates fitted values for one logtitre for all bootstrap fit results
#'
#' @param logtitre One value of logtitre to calculate fitted values for
#' @param bootfit_wide Widened bootstrap results
#' @param threshold Threshold logtitre to calculate relative protection for
fit_for_one_logtitre <- function(logtitre, bootfit_wide, threshold = log(5)) {
  bootfit_wide %>%
    mutate(
      fit_lin = b0 + bx * logtitre,
      threshold_lin = b0 + bx * threshold,
      fit_og = 1 - 1 / (1 + exp(fit_lin)),
      threshold_og = 1 - 1 / (1 + exp(threshold_lin)),
      fit_rel = fit_og / threshold_og
    ) %>%
    select(-contains("threshold"), -fit_lin) %>%
    pivot_longer(contains("fit"), names_to = "fit_type", values_to = "fit") %>%
    mutate(
      logtitre = logtitre,
      prot = 1 - fit,
      prot_type = str_replace(fit_type, "fit_", "")
    )
}

#' Summarises the fitted values by obtaning the quantiles of the distribution
#' for protection at different values of logtitre
summarise_fit <- function(fit) {
  fit %>%
    group_by(prot_type, logtitre) %>%
    summarise(prot_quant = list(quantile(prot, c(0.025, 0.5, 0.975)))) %>%
    ungroup() %>%
    unnest_longer(
      prot_quant,
      values_to = "prot", indices_to = "quant"
    )
}

# Script ======================================================================

# Bootstrap results. boot-lr.csv is generated by boot-lr.R
bootfit <- read_csv(
  file.path(fit_dir, "boot-lr.csv"),
  col_types = cols()
)

# Convert to wide
bootfit_wide <- bootfit_widen(bootfit)

# Calculate the quantiles for the predictor at a range of logtitre values
logtitres <- seq(0, 8, length.out = 101)
fit_preds <- map_dfr(logtitres, fit_for_one_logtitre, bootfit_wide, log(5))

# Summarise the fitted values
fit_summ <- summarise_fit(fit_preds)

# Save the summary
write_csv(fit_summ, file.path(fit_dir, "predict-boot-lr.csv"))
