# Plots the cox predictions for protection

library(tidyverse)

# Directories used
fit_dir <- here::here("model-fit")
prot_plot_dir <- here::here("protect-plot")

# Functions ===================================================================

source(file.path(fit_dir, "read_predict.R"))

#' Converts the bootstrap summary to wide
#'
#' @param bootsum Bootstrap summary (predictions)
#' @param type 'og' for absolute protection; 'rel' for relative
widen_summary <- function(bootsum, type) {
  bootsum %>%
    filter(prot_type == type) %>%
    select(-prot_type) %>%
    mutate(
      quant = recode(
        quant,
        "2.5%" = "protection_low", "50%" = "protection",
        "97.5%" = "protection_high"
      )
    ) %>%
    pivot_wider(names_from = "quant", values_from = "prot")
}

#' Generates the plot
#'
#' @param cox_fit Predictions from the cox model
gen_plot <- function(cox_fit) {
  cox_fit %>%
    ggplot(aes(logtitre, protection)) +
    theme_bw() +
    theme(
      panel.grid.minor.y = element_blank()
    ) +
    coord_cartesian(
      xlim = c(log(5), log(1280)),
      ylim = c(0, 1)
    ) +
    scale_x_continuous(
      "Titre",
      breaks = log(5 * 2^(0:8)),
      labels = 5 * 2^(0:8),
      minor_breaks = log(7.5 * 2^(0:8)),
    ) +
    scale_y_continuous(
      "Protection",
      labels = scales::percent_format()
    ) +
    geom_ribbon(
      aes(ymin = protection_low, ymax = protection_high),
      alpha = 0.5
    ) +
    geom_line()
}

#' Saves the plot to the same folder as the script
#'
#' @param plot A ggplot to save
#' @param name Name to save by. Will be prefixed with `protect-`
save_pred_plot <- function(plot, name) {
  ggsave(
    file.path(prot_plot_dir, glue::glue("protect-{name}.pdf")),
    plot,
    width = 12, height = 7.5, units = "cm"
  )
}

# Script ======================================================================

# Predictions generated by scripts in the model fit folder

boot_lr <- read_predict("boot-lr")

all_preds <- list(
  cox = read_predict("cox"),
  lr = read_predict("lr"),
  sclr = read_predict("sclr") %>%
    rename(
      protection_low = prot_l, protection_high = prot_u,
      protection = prot_point
    ),
  "boot-lr" = widen_summary(boot_lr, "og"),
  "boot-lr-rel" = widen_summary(boot_lr, "rel")
)

# Plots of protection
pred_plots <- map(all_preds, gen_plot)

# Save plots to the same directory as the script
iwalk(pred_plots, save_pred_plot)
