# Plots the logistic predictions for protection

library(tidyverse)
library(here)

# Directories used
lr_fit_dir <- here("logistic-regression", "model-fit")
lr_fit_boot_dir <- here("logistic-regression", "model-fit-boot")
lr_fit_plot_dir <- here("logistic-regression", "model-fit-plot")

# Functions ===================================================================

gen_plot <- function(lr_fit) {
  lr_fit %>%
    ggplot(aes(logtitre, protection)) +
    theme_bw() +
    theme(
      panel.grid.minor.y = element_blank()
    ) +
    coord_cartesian(
      xlim = c(log(5), log(1280)),
      ylim = c(0, 1)
    ) +
    scale_x_continuous(
      "Titre",
      breaks = log(5 * 2^(0:8)),
      labels = 5 * 2^(0:8),
      minor_breaks = log(7.5 * 2^(0:8)),
    ) +
    scale_y_continuous(
      "Protection",
      labels = scales::percent_format()
    ) +
    geom_ribbon(
      aes(ymin = protection_low, ymax = protection_high),
      alpha = 0.5
    ) +
    geom_line()
}

widen_summary <- function(bootsum, type) {
  bootsum %>%
    filter(prot_type == type) %>%
    select(-prot_type) %>%
    mutate(
      quant = recode(
        quant,
        "2.5%" = "protection_low", "50%" = "protection",
        "97.5%" = "protection_high"
      )
    ) %>%
    pivot_wider(names_from = "quant", values_from = "prot")
}

save_plot <- function(plot, name) {
  ggsave(
    file.path(lr_fit_plot_dir, glue::glue("{name}.pdf")),
    plot,
    width = 12, height = 7.5, units = "cm"
  )
}

# Script ======================================================================

# Fitted values. Run `fit.R` in the `model-fit` folder to generate `fit.csv`
lr_fit <- read_csv(file.path(lr_fit_dir, "fit.csv"), col_types = cols())

# Summary of fitted values via bootstrap. Generated by `summary-boot.R`
lr_fit_boot <- read_csv(
  file.path(lr_fit_boot_dir, "fit-summary.csv"),
  col_types = cols()
)

# Plots of protection
lr_plot <- gen_plot(lr_fit)
lr_plot_boot_og <- widen_summary(lr_fit_boot, "og") %>% gen_plot()
lr_plot_boot_rel <- widen_summary(lr_fit_boot, "rel") %>% gen_plot()

# Save plot to the same directory as the script
iwalk(
  list(
    "protection" = lr_plot,
    "protection_boot" = lr_plot_boot_og,
    "protection_boot_rel" = lr_plot_boot_rel
  ),
  save_plot
)
