# Plot the simulated logistic and scaled logit data

library(tidyverse)

# Directories used
data_dir <- here::here("data")
data_plot_dir <- here::here("data-plot")

# Functions ===================================================================

source(file.path(data_dir, "read_data.R"))

#' Summarises the simulated binary data
#'
#' Calculates infected proportion for different titre groups
#'
#' @param data Simulated binary data (logistic or scaled logit)
summ_data_sim_bin <- function(data) {
  data %>%
    mutate(
      titre = exp(logtitre),
      titre_group = cut(
        titre, c(0, 10 * 2^(0:7), Inf),
        dig.lab = 4, right = FALSE
      )
    ) %>%
    group_by(titre_group) %>%
    summarise(
      n = n(),
      prop = sum(status) / n
    )
}

#' Plots simulated data
#'
#' @param summ Summarised simulated data
plot_sim_bin <- function(summ) {
  summ %>%
    ggplot(aes(titre_group, prop)) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 30, hjust = 1)
    ) +
    coord_cartesian(ylim = c(0, 1)) +
    scale_y_continuous(
      "Infected proportion",
      labels = scales::percent_format()
    ) +
    scale_x_discrete("Titre range") +
    geom_point() +
    ggrepel::geom_text_repel(aes(label = n)) +
    labs(caption = "Numbers are total group counts")
}

source(file.path(data_plot_dir, "save_data_plot.R"))

# Script ======================================================================

# Simualted data. Generated by data/sim.R
datasets_sim_bin <- map(
  c("lr" = "sim-lr", "sclr" = "sim-sclr"),
  read_data
)

# Summarise the simulated data for plotting
summaries_sim_bin <- map(datasets_sim_bin, summ_data_sim_bin)

# Plot the summarised data
plots_sim_bin <- map(summaries_sim_bin, plot_sim_bin)

# Save the plot to the same folder as the script
iwalk(plots_sim_bin, save_data_plot)
