name: GenerateResults

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-results:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install R
      uses: r-lib/actions/setup-r@master
    
    - name: Install Snakemake
      run: | 
        sudo apt-get install snakemake
        sudo -H python3 -m pip install --upgrade snakemake

    - name: Install R packages
      run: sudo Rscript dependencies.R

    - name: snakemake all
      run: snakemake all --cores 1
    
    - uses: actions/upload-artifact@v1
      with:
        name: data
        path: data
