name: GenerateResults

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-results:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add R repository
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
    
    - name: Install Snakemake
      run: | 
        sudo apt-get install snakemake
        sudo -H python3 -m pip install --upgrade snakemake

    - name: Install R package dependencies
      run: sudo apt-get install libcurl4-openssl-dev libxml2-dev libssl-dev

    - name: Cache packrat
      uses: actions/cache@v1
      env:
        cache-name: cache-packrat
      with:
        path: "packrat/lib"  
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('packrat/packrat.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
    
    - name: Restore packrat snapshot
      run: R --vanilla -f .Rprofile --args --bootstrap-packrat

    - name: snakemake all
      run: snakemake all --cores 1
    
    - uses: actions/upload-artifact@v1
      with:
        name: data
        path: data
